### ISSUE TITLE
ImageLoader throws exception on Windows

### ISSUE THREAD

**Issue by tjclement** [Bizboard/arva-mvc#13]
When using arva-js/utils/ImageLoader.js on Windows, an exception is thrown because the path being looked up begins with 'c:/c:/'.

This is because the full image URL is 'file:///c:/[..]', and we strip out the 'file://' part. This leaves '/c:/[..]' with a leading forward slash, which works on *nix, but adds 'c:/' on Windows.

We need to look into changing this behaviour to support OS X, Linux, and Windows.

**Comment by tjclement** [comment]
Fixed in IE11 branch, awaiting release in mainstream

**Comment by ManuelOverdijk** [comment]
This is fixed in release v1.2.1
