### ISSUE TITLE
Some insertions causes viewsequence corruption

### ISSUE THREAD

**Issue by Karolusrex** [Bizboard/arva-mvc#8]
The 0.3.6 [remark of famous-flex](https://github.com/IjzerenHein/famous-flex/releases) says 'ViewSequence has various known issues when inserting/removing/moving items which causes "ViewSequence corruptions". '. 

We seem to be causing one when inserting an element to the head and back at the same time on a DBSV. 

Quick fix:

```
if(insertIndex === 0 && this._dataSource.length > 0){
            this.insert(1, newSurface);
            this.swap(0, 1);
        } else {
            this.insert(insertIndex, newSurface);
        }
```

in `_addItem` of DataBoundScrollView.js

**Comment by tjclement** [comment]
Workaround added in DBSV by @Karolusrex, so closing this issue
